version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/flutter_db
    volumes:
      - ./backend:/app
      - media:/app/media
    networks:
      - app_network

  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flutter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network

  # Flutter веб-приложение (опционально, можно закомментировать если не нужно)
  flutter_app:
    build: .
    container_name: flutter_web
    ports:
      - "8081:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:8000
    networks:
      - app_network

volumes:
  postgres_data:
  media:

networks:
  app_network:
    driver: bridge