"""add metadata column to users

Revision ID: c3eefe601521
Revises: fb01b1e9a27f
Create Date: 2026-03-11 11:38:50.125486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3eefe601521'
down_revision: Union[str, None] = 'fb01b1e9a27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'metadata')
    # ### end Alembic commands ###
